---
name: Renew Lets Encrypt Certificates

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: Dev
        required: true

concurrency:
  group: letsencrypt
  cancel-in-progress: false

env:
  USE_ENV_VARS_NOT_FILES: true
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

jobs:
  renew_letsencrypt_certs:
    name: Renew Lets Encrypt Certificates
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'Dev' }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout AzureTRE upstream
        uses: actions/checkout@v4
        with:
          repository: microsoft/AzureTRE
          path: AzureTRE

      - name: Install specific Azure CLI version
        run: |
          AZ_DIST=$(lsb_release -cs)
          AZ_VER=2.73.0
          sudo apt-get update
          sudo apt-get install azure-cli="${AZ_VER}-1~${AZ_DIST}" --allow-downgrades
          az version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Set environment variables
        run: |
          echo "AZURETRE_HOME=${{ github.workspace }}/AzureTRE" >> $GITHUB_ENV

      - name: Renew Certificates
        shell: bash
        env:
          ARM_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          AZURE_ENVIRONMENT: ${{ vars.AZURE_ENVIRONMENT }}
          TRE_ID: ${{ secrets.TRE_ID }}
          TF_VAR_terraform_state_container_name: ${{ secrets.TERRAFORM_STATE_CONTAINER_NAME || 'tfstate' }}
          TF_VAR_mgmt_resource_group_name: ${{ secrets.MGMT_RESOURCE_GROUP_NAME }}
          TF_VAR_mgmt_storage_account_name: ${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
          PRIVATE_AGENT_SUBNET_ID: ${{ secrets.PRIVATE_AGENT_SUBNET_ID }}
        run: |
          sudo apt-get install -y python3 python3-venv libaugeas0
          python3 -m venv /opt/certbot/
          /opt/certbot/bin/pip install --upgrade pip
          /opt/certbot/bin/pip install certbot
          make -C AzureTRE letsencrypt

